### ISSUE TITLE
Moodlight.ino

### ISSUE THREAD

**Issue by rnoxious** [sweebee/Arduino-home-automation#6]
I know this is a long shot. I'm hoping you still monitor this. I'm having issues getting the colors to change. Can you offer some advice?

**Comment by sweebee** [comment]
I haven't used it in years but if I look back at my code, you can send an HEX color code with the message type ```V_VAR1```.

For Example: ```#FF0000```.

**Comment by rnoxious** [comment]
I just found the spot in the controller where you can enter the hex. Thank you.
